annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - media
  truecharts.org/grade: U
apiVersion: v2
appVersion: 4.7.8.0
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.9.4
description: Emby Server is a home media server
home: https://truecharts.org/docs/charts/stable/emby
icon: https://truecharts.org/img/hotlink-ok/chart-icons/emby.png
keywords:
- jellyfin
- plex
- emby
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: emby
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/emby
- https://hub.docker.com/r/linuxserver/emby
- https://github.com/linuxserver/docker-emby.git
type: application
version: 12.0.2
